### ISSUE TITLE
로그인 로직 변경 요청

### ISSUE THREAD

**Issue by p3chaeyeon** [bitcamp-aiaas-9/FilmNote#30]
## 관리자
- 관리자 로그인 후 index.jsp 이동 (현재 로그인 후 주창 : http://localhost:8080/FilmNote/admin/adminSignIn.do)
- 관리자 로그인 후 "관리자님" 버튼 클릭 시 /admin/movieList.jsp 로 이동 
  (현재 "관리자님" 클릭 후 주소 : http://localhost:8080/FilmNote/admin/adminEdit.do)
  (제 브랜치에서는 movieBoard.jsp 를 movieList.jsp 로 변경했으니 경로 movieList.jsp 로 해주세요 추후 머지할 예정입니다.)
- 관리자 로그아웃 후 index.jsp 이동 (현재 로그아웃 후 주소 : http://localhost:8080/FilmNote/admin/adminLogOut.do )

## 사용자
- 사용자 로그인 후 index.jsp 이동 (현재 로그인 후 주소 : http://localhost:8080/FilmNote/user/userSignIn.do)
- 사용자 로그아웃 후 index.jsp 이동 (현재 로그아웃 후 주소 : http://localhost:8080/FilmNote/user/userLogOut.do)

이렇게 바꿔주세요!

**Comment by KimSeongChan97** [comment]
수정해서 곧 올릴게요
